use log::warn;
use poise::{
    serenity_prelude as serenity,
    serenity_prelude::{
        ComponentInteraction, CreateActionRow, CreateButton, CreateEmbed, CreateEmbedFooter,
        CreateInteractionResponse, CreateMessage,
    },
    CreateReply,
};
use rand::seq::SliceRandom;
use rand::Rng;

use crate::{commands::EMBED_COLOR, Error};

/// Choose between a truth or a dare
#[poise::command(slash_command, broadcast_typing)]
pub async fn truth_or_dare(ctx: poise::Context<'_, (), Error>) -> Result<(), Error> {
    let truth_button = CreateButton::new("tod_truth")
        .label("Truth")
        .style(serenity::ButtonStyle::Success);
    let dare_button = CreateButton::new("tod_dare")
        .label("Dare")
        .style(serenity::ButtonStyle::Danger);
    let random_button = CreateButton::new("tod_random")
        .label("Random")
        .style(serenity::ButtonStyle::Primary);

    ctx.send(
        CreateReply::default()
            .embed(
                CreateEmbed::new()
                    .title("Truth or Dare")
                    .description("Choose between getting a truth or a dare!")
                    .color(EMBED_COLOR),
            )
            .components(vec![CreateActionRow::Buttons(vec![
                truth_button,
                dare_button,
                random_button,
            ])]),
    )
    .await?;

    Ok(())
}

pub(crate) async fn receive_interaction(
    ctx: &serenity::Context,
    interaction: &ComponentInteraction,
) {
    let mut int_type = interaction.data.custom_id.as_str();

    if interaction.data.custom_id.as_str() == "tod_random" {
        // pick a number between 1 and 2

        let mut rng = <rand::rngs::SmallRng as rand::SeedableRng>::from_entropy();
        let random_number: usize = rng.gen_range(1..3);
        if random_number == 1 {
            int_type = "tod_truth";
        }
        if random_number == 2 {
            int_type = "tod_dare";
        }
    }

    match int_type {
        "tod_truth" => {
            let truth = TRUTHS
                .choose(&mut rand::thread_rng())
                .expect("Unreachable, TRUTHS will never be empty");
            ctx.http
                .send_message(
                    interaction.channel_id,
                    Vec::new(),
                    &CreateMessage::default().embed(
                        CreateEmbed::new()
                            .title("Here's your truth!")
                            .description(*truth)
                            .color(EMBED_COLOR)
                            .footer(
                                CreateEmbedFooter::new(format!(
                                    "Requested by: {}",
                                    interaction.user.name
                                ))
                                .icon_url(interaction.user.avatar_url().unwrap_or_default()),
                            ),
                    ),
                )
                .await
                .expect("Failed to send message");
        }
        "tod_dare" => {
            let dare = DARES
                .choose(&mut rand::thread_rng())
                .expect("Unreachable, DARES will never be empty");
            ctx.http
                .send_message(
                    interaction.channel_id,
                    Vec::new(),
                    &CreateMessage::default().embed(
                        CreateEmbed::new()
                            .title("Here's your dare!")
                            .description(*dare)
                            .color(EMBED_COLOR)
                            .footer(
                                CreateEmbedFooter::new(format!(
                                    "Requested by: {}",
                                    interaction.user.name
                                ))
                                .icon_url(interaction.user.avatar_url().unwrap_or_default()),
                            ),
                    ),
                )
                .await
                .expect("Failed to send message");
        }
        _ => {
            warn!(
                "Unhandled interaction in truth or dare: {:?}",
                interaction.data.custom_id
            );
        }
    }

    interaction
        .create_response(&ctx.http, CreateInteractionResponse::Acknowledge)
        .await
        .expect("Failed to create response to interaction");
}

pub static TRUTHS: [&str; 1313] = [
	"If you could change one thing about your family, what would it be?",
	"What is socially acceptable today that you think won't be in 10 years?",
	"What is something that you absolutely will not put up with?",
	"What do you look for in a potential love interest?",
	"If you were going to get canceled on Twitter, what would it be for?",
	"If someone were to sum you up with a phrase, what would that phrase be?",
	"What's the biggest wager you've ever made?",
	"What's something/someone you will never forget?",
	"What's the longest you've purposely left someone on read?",
	"Have you ever sleep-walked?",
	"Have you ever done something to intentionally make your ex jealous?",
	"Have you ever eaten a bug?",
	"If there are 100 people, how many would be more patient than you?",
	"How long have you gone without showering?",
	"What's the story behind why you replaced the last phone you had?",
	"What is your shoe size?",
	"What's your favorite school subject?",
	"Admit to something dumb you did recently.",
	"Do you prefer apple or android?",
	"If you were to be famous for something, what would that be?",
	"If you could get rid of one household chore, what would it be?",
	"Are you where you thought you’d be 10 years ago?",
	"Did you ever have a huge rival? Was the rivalry friendly or fierce?",
	"Have you ever had a crush on someone here?",
	"What is the most annoying thing that one of your siblings has done?",
	"What is your deepest, darkest secret?",
	"What kind of parent do you think you will be?",
	"What makes you happy?",
	"Who's your idol?",
	"How do you approach life?",
	"Did you ever stay in a relationship because of money?",
	"What was the most physically painful experience of your life?",
	"What are you wearing?",
	"Which two people here would make the worst couple?",
	"How did you get away with cheating on a test?",
	"What would you do if you were going to die in 3 days?",
	"What piece of art has had a large impact on you?",
	"What do you think might be hiding in your closet at night?",
	"Do you wear your same underwear for more than one day?",
	"What's something (idea, current event, fear) that you find deeply unsettling?",
	"What is your favorite kind of cheese?",
	"What kind of pajamas do you wear?",
	"What's the most difficult thing that you still do each day?",
	"Do you have a favorite sibling?",
	"What foods did you used to like but don't anymore?",
	"Do you keep a diary or a journal?",
	"Would you ever cheat off a friend's paper?",
	"Do you pick scabs?",
	"If you could assign one household chore to someone else, what would it be?",
	"What was your worst workplace experience?",
	"Do you have any family members that are mechanics?",
	"What is your favorite food?",
	"What's the meanest nickname you've ever given someone?",
	"Have you ever snuck out of the house?",
	"What types of things do you doodle?",
	"What is the one dare you would object to?",
	"What is your typing speed?",
	"Have you ever had a missed connection encounter?",
	"Have you ever cried during a movie? If so, which one?",
	"Math or science?",
	"Who on this server do you talk to the most and why?",
	"Do you love your partner?",
	"Do you, or did you in the past, have any strange habits?",
	"How many best friends have you had during your lifetime?",
	"If you were to give 'don't do what I did” advice to a younger person, what would it be?",
	"What was the best moment of your life?",
	"Do you like summer or winter more? Why?",
	"What's your story about being under intense pressure and how did you handle it?",
	"Why did your last relationship end?",
	"If you write a book, what would it be about?",
	"Have you ever gone to the bathroom in the pool?",
	"Have you ever spread a rumor?",
	"Have you ever been part of a protest or riot?",
	"Is there anything that most people find cute that creeps you out?",
	"What made you fall in love with your crush/partner?",
	"If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
	"Who's the worst person you've ever met?",
	"Do you miss your ex?",
	"What do you hope to be an expert about at some point in your life?",
	"What quote do you want on your tombstone?",
	"How long have you been in the server?",
	"Have you ever lied to your best friend's face? What did you lie about?",
	"What is your dream job?",
	"What does nobody want to talk about, but really should?",
	"When was the last time you sang to yourself? What about to someone else?",
	"What's a bad habit that you have?",
	"If you had a million dollars, what would you do with all of your money?",
	"Do you wash your hands every time after you go to the bathroom?",
	"If you had the choice to live on your own right now, would you do it?",
	"If you could be invisible, what would you do?",
	"If you were allowed to marry more than one person, would you?",
	"If you could live anywhere in the world, where would you live?",
	"If you suddenly won the lottery, what would you spend it on?",
	"What's the most embarrassing nickname you've ever had?",
	"What's the worst thing you can remember that's happened to you?",
	"If you had to change your name, what would you change it to?",
	"Have you ever blamed a pet for something you did?",
	"If you could only be fluent in one language (excluding your native language), what would you choose?",
	"Name something you've always wanted, but is too expensive to buy.",
	"Have you ever stolen money from your parents?",
	"If you could go back in time and erase one thing you did in the past, what would it be?",
	"What's your favorite junk food?",
	"Which band or artist do you secretly like?",
	"What's one thing you think you should be doing more often?",
	"Do you like otters?",
	"When did you join Discord?",
	"If you could dye your hair any color, what color would you pick?",
	"Have you ever committed a crime? If so, what was it?",
	"What is the most embarrassing thing you have put on social media?",
	"Have you ever climbed a tree?",
	"Have you ever had cosmetic surgery?",
	"Have you ever laughed at a totally inappropriate moment?",
	"Are you a 'glass half full' or a 'glass half empty' person? (optimist or pessimist)",
	"Are you fragile?",
	"Do you have any pets?",
	"Have you ever gotten a sibling in trouble for something you did?",
	"If you could kiss one celebrity, who would it be?",
	"What question have people recently been constantly asking you?",
	"Is it true that you have more than 4 exes?",
	"Have you ever had Discord nitro?",
	"How far would you go on a first date?",
	"If you knew you could live forever, how would you spend your days differently?",
	"What's your biggest shopping addiction?",
	"Would you prefer to be the opposite/different gender?",
	"What food have you never tried?",
	"What would be a perfect day for you?",
	"What's something that was completely out-of-character that you did?",
	"What's the most disgusting food you've ever eaten?",
	"What was the most embarrassing thing you accidentally texted to the wrong person?",
	"What do you want to do when you are retired?",
	"What is the most embarrassing music you listen to?",
	"What's the most recent interesting conversation you had?",
	"What's the worst decision you've made?",
	"What do you think about the space-time continuum?",
	"What kind of bird would you like to be?",
	"What do you want to be when you grow up?",
	"What have you found more helpful than you ever imagined it could be?",
	"What was the best phase in your life?",
	"What is the strangest way you met one of your friends?",
	"Have you ever stolen something from a neighbor?",
	"What food would you never give up in a million years?",
	"Have you ever got the giggles at the wrong time? Where and when?",
	"Do you practice what you say before making a call? Why?",
	"If you could know one thing from the past, what would it be?",
	"Have you ever eaten food from the floor?",
	"What's your favorite daily routine?",
	"Are you vegetarian/vegan?",
	"What is your favorite thing about the opposite gender (or the gender that you are attracted to?)",
	"If you could make one rule that everyone had to follow, what would it be?",
	"If you could pick one season to stay year-round, which would you pick?",
	"Would you kiss your best friend?",
	"What's something that irrationally irritates you?",
	"Do you have any allergies?",
	"Who here is your best friend?",
	"How do you best like your ice-cream?",
	"If you could find the answer to one question about your past, present, or future, what would you ask?",
	"If you were to devote your life to art, what type of art would that be?",
	"Do you prefer making a first step in relationship or do you prefer your SO to do it?",
	"Which came first, the chicken or the egg?",
	"If there was no such thing as money, what would you do with your life?",
	"What is the most exotic food that you have ever eaten?",
	"What was one of the best moments of your life?",
	"What was the strangest thing you ever ate?",
	"Have you ever lied to your parents about if you were in classes or not?",
	"What would be the first thing you do if you woke up as the opposite/different sex?",
	"Have you ever been hypnotized?",
	"Have you ever been tempted to cheat on someone?",
	"What is the latest thing you bought?",
	"What's something that you know you should start, but haven't?",
	"Where did you used to think babies come from?",
	"Do you consider telling white lies to be okay?",
	"Where are you from?",
	"Has your partner ever embarrassed you?",
	"What's something that your parents did to you that you will never do to your kids?",
	"How many siblings do you have?",
	"If you had to choose, who would you pick to exchange your girlfriend/boyfriend with?",
	"What was the most painful breakup you have ever had?",
	"Do you have any phobias?",
	"Who have you met only one time that left a huge impression on you?",
	"What are some of your dreams for the future?",
	"Who is wearing the worst outfit in the room?",
	"If you had to pick a single word to describe this year so far, what would it be?",
	"Have you ever practiced kissing on something/someone?",
	"Do you think rain smells good?",
	"What’s one movie you’re embarrassed to admit you enjoy?",
	"What is something you feel is unacceptable that is still being done today?",
	"Who do you like the most in this server?",
	"What action from your past would put you in jail if law enforcement ever found out about it?",
	"What's the weirdest thing you've done?",
	"What's one thing you wish you could change?",
	"Why did you stop liking your previous crush?",
	"Name a time when you used somebody for your personal gain.",
	"What's the most embarrassing thing in your web history?",
	"If you had the choice to go back in time or into the future, which would you choose?",
	"Do you still sleep with a teddy bear?",
	"What are your favorite five words at the moment?",
	"What is the silliest thing that you have ever done?",
	"Have you ever had a crush on someone that your best friend has dated?",
	"What have you been thinking about lately that has kept you up at night?",
	"What is your favorite sports team?",
	"What is the most embarrassing song you listen to?",
	"Have you ever peeked at Christmas presents early?",
	"What is your best childhood memory?",
	"Did you have an anime phase?",
	"If you could go to prom with anyone, who would it be?",
	"What's your close call story?",
	"What is your favorite Discord bot? 😉",
	"If you could add any bot to this server, what bot would you add?",
	"How many chances do you give a person before you write them off?",
	"What's your favorite website?",
	"What's the most useless thing you know?",
	"How would a random stranger describe you? How accurate would that be?",
	"What is the most selfish thing you do that you're okay with?",
	"What's the most expensive thing you've stolen?",
	"What is your worst habit?",
	"What's your story about breaking the law?",
	"What is the most expensive thing you own?",
	"What's your least favorite song?",
	"What is the worst advice anyone has ever given you?",
	"What evil genius would you like to be?",
	"What parts of your body do you shave?",
	"How much money do you make?",
	"Have you ever been caught cheating in school?",
	"Have you ever met a celebrity?",
	"What’s something you’re afraid to tell people?",
	"What's the craziest thing you would do to make a crush like you back?",
	"What's the most embarrassing thing your parents have caught you doing?",
	"Have you ever peed in the pool?",
	"When have you loved someone who has not loved you back?",
	"Do you believe in aliens?",
	"When have you had to walk away in shame?",
	"Do you think you look worse or better than most people you know?",
	"What are you currently doubting in your life?",
	"When was the last memorable sunrise you witnessed?",
	"Do you look forward to being an adult? If already, do you miss being a kid?",
	"Who do you pretend to like, but actually don't?",
	"What makes you bored out of your mind?",
	"How many romantic interests do you think you will have for the rest of your life?",
	"What's the biggest mistake you've ever made while cooking?",
	"Have you ever peed in a pool?",
	"What is your favorite movie/tv/video game character?",
	"What's the earliest memory of your life?",
	"What was the best thing you learned in the past year?",
	"Can you speak a different language?",
	"What's the most embarrassing conversation you've had through text messages?",
	"Who do you secretly think is hot?",
	"What is the most bizarre dream you've ever had?",
	"If you could get rid of any school subject, which one?",
	"Have you ever used lunch money on something you shouldn’t?",
	"What happened on the worst day of your life?",
	"How much would you do to get your dream guy/girl/partner?",
	"What was the last meltdown that you witnessed?",
	"Do you snore?",
	"If you had to choose brains or beauty, which would you pick?",
	"How often do you lie to other people?",
	"What do you like to do that's considered touristy?",
	"Have you ever acted in self defense?",
	"Have you ever cried from watching a TV show or a movie?",
	"What's something that you think you may have been the only person in the world to ever do?",
	"What are the things on your 'bucket' list?",
	"Which app do you use the most?",
	"What's something commonly done today that you think people will wonder why anyone would ever do that fifty years from now?",
	"Who here would you trust all your memories with?",
	"What's your opinion on social media?",
	"What is the quickest way for you to lose respect for someone?",
	"Do you believe in love at all?",
	"What's something that you recently learned that everyone else already knew?",
	"Have you ever been intimate in a public place?",
	"Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?",
	"Would you want to know how you die if you could?",
	"Have you ever been bullied?",
	"What's your current biggest worry?",
	"What is the meanest thing that you have done?",
	"What's the worst thing one of your friends or ex-friends has done to you?",
	"What is the most embarrassing thing that has happened to you this year?",
	"What is something you wish you were better at?",
	"What do you look most for in a person?",
	"What's the most you've ever donated to a Twitch stream?",
	"What is the last thing that you totally overreacted to?",
	"Have you ever had a terrible house guest? If so, what happened?",
	"Have you ever gotten into a physical altercation with anyone?",
	"Have you ever gone without wearing any underwear for a full day?",
	"Who here are you most scared of?",
	"Have you ever taken a duck face selfie?",
	"What is a thing that nobody knows about you yet?",
	"What would be the best and worst part of being a cat in your opinion?",
	"How do you think you will die?",
	"Talk about the craziest thing that you overheard.",
	"Do you have any irrational fears?",
	"What does everyone think is true about you, but isn't?",
	"Who here is best at flirting?",
	"What do you think is your most creative ability?",
	"Do you think people see you the same way you see yourself?",
	"What was one unrealistic dream you had as a child?",
	"Have you ever had a near-death experience?",
	"What's your go-to funny story now, but was horrendous at that moment?",
	"What is something that you have never told anyone?",
	"Have you ever asked someone out and got rejected? What happened?",
	"What's your trick for getting attention from a crush?",
	"What is your favorite TV show?",
	"What's the last thing that you broke and how did it happen?",
	"Are there any rules or social norms that piss you off?",
	"If you could wake up tomorrow having gained any one quality or ability, what would it be?",
	"Do you have anything in your bed for comfort when you sleep?",
	"When was the last time you did something nice for somebody else?",
	"Do you have a job? If so, what is your favorite thing about it?",
	"Who's your favorite person in this server?",
	"Do you simp for any streamers?",
	"Is there a part of your culture that you don't like?",
	"What is the most embarrassing thing that your parents have caught you doing?",
	"What's your \"famous person\" story?",
	"If you had 5 extra hours a day, what would you spend them on?",
	"What has been one of your most embarrassing moments?",
	"How would you spend your time if you were a billionaire?",
	"Have you ever cheated on an exam?",
	"What was your first impression of everyone here?",
	"What do most of your friends think about you that is completely untrue?",
	"If you had the opportunity to look through someone's email without them knowing, would you?",
	"Have you ever had a run-in with the law?",
	"Have you ever been punished for something you didn't do?",
	"Do you like where you live?",
	"What is your least favorite physical or emotional attribute?",
	"What's the sketchiest thing you've seen/heard?",
	"What country would you like to live in if you had the chance?",
	"Did you get a lot of valentines as a kid?",
	"What are some of your strangest \"shower thoughts\"?",
	"What's your idea of a perfect, romantic date?",
	"What's the closest you've ever come to cheating?",
	"What's the worst thing that happened to you today?",
	"Who affects you the most when they are sad in the server?",
	"Have you ever waited outside for the mail to arrive?",
	"How old is the oldest person you've dated?",
	"What's the best meal you've ever had?",
	"Which fictional character would you love to marry?",
	"What is something that will instantly annoy you?",
	"Who's the hottest person at work or school?",
	"How many people have you been with?",
	"Talk about a time that you failed in life.",
	"What could make you get back together with your ex?",
	"If you had to choose between being in a choir and being in a play, what would you choose?",
	"What was your worst kiss?",
	"Do you have a social media account that you hide?",
	"Who in this server is the most likely to get rich?",
	"Are you wearing underwear?",
	"How long could you without eating your favorite food?",
	"If you could have any superpower, what would you choose?",
	"Do others think you are annoying?",
	"Have you ever thought of cheating on your partner?",
	"Which Disney character do you think is the hottest?",
	"Have you ever pressed charges on anyone?",
	"How long was your longest relationship?",
	"Do you apologize after an argument?",
	"Have you ever faked being drunk?",
	"What has been your biggest financial mistake?",
	"What's the last thing you complained about?",
	"If you could accomplish three things in life what would they be?",
	"Tell an embarrassing tale about yourself.",
	"What is your favorite place in the world?",
	"Who is your favorite teacher, and why?",
	"What do you wish you had learned five years before you did?",
	"What is your current favorite TV show? What was it 5 years ago?",
	"What is the longest time you have ever been grounded?",
	"How often do you think you lie to yourself?",
	"What's the dumbest dare you've done?",
	"Do you keep a diary/notebook?",
	"Have your parents ever given you the 'birds and bees' talk?",
	"What's your knowing just enough to be dangerous story?",
	"When was the last time you exercised?",
	"What's the most interesting thing you have in your pockets right now?",
	"Can you lick your elbow?",
	"What was your most embarrassing moment?",
	"Who is the most annoying person in the room?",
	"What was the longest time you've gone without sleeping?",
	"How many things you currently own do you think you could throw away and not notice a difference in your life?",
	"Do you like romantic movies?",
	"Imagine that you're on a deserted island and can only bring 2 things with you. What would they be?",
	"Has someone ever done a random act of kindness to you?",
	"Are you in any sports?",
	"Do you have any unusual fears?",
	"What is your most embarrassing moment?",
	"Hot or not: belly button piercings?",
	"Have you ever said you finished your dinner when you really didn’t?",
	"What's your favorite anime?",
	"Who would you pick to exchange your partner with if you had to choose?",
	"If you could be any celebrity, who would you be and why?",
	"What is a fear you overcame?",
	"Which relationship do you prefer: a wild, passionate one or a quiet calm one?",
	"What is your dream college?",
	"What games do you have on your phone?",
	"How many times do you take care of yourself a week?",
	"Who is the most attractive person in the room?",
	"What truth or dare question do you not want to answer?",
	"What's your favorite film?",
	"What is your favorite childhood memory?",
	"What does it mean to \"live a good life\" in your opinion?",
	"Have you ever gotten arrested or almost gotten arrested?",
	"Have you ever had a dream about one of your relatives?",
	"Name someone you highly envy or are downright jealous of.",
	"Do you like pancakes?",
	"What is your love language?",
	"What's the most difficult thing about being you?",
	"What are some ways you cheat on chores?",
	"What's your least favorite Truth or Dare question?",
	"What's your most self-destructive behavior?",
	"Which of your past teachers would you like to sit down with and talk to today?",
	"Have you ever been called ugly?",
	"Is there anything that makes you far angrier than it should?",
	"Have you ever eaten food that you dropped on the ground?",
	"Can you see yourself marrying your high school sweetheart?",
	"If you could live in any fictional universe which one would it be?",
	"How do you think your reality differs from others you know?",
	"What makes you jealous?",
	"Have you ever been arrested?",
	"What is your secret talent?",
	"What's the most embarrassing situation you've ever farted in?",
	"Do you remember what the first school report you wrote was about?",
	"What do you like about your ex?",
	"Describe your dream home",
	"Who is your favorite fictional character?",
	"If you had to date anyone here who would it be?",
	"What motivates you the most?",
	"Have you ever been caught copying someone else's work?",
	"If you could have your own business one day, what would it be?",
	"If you could play a prank on any historical figure, who would you pick and what prank would you do?",
	"What do you find you recently spend a lot of time wondering about?",
	"What's a food you vow never to eat?",
	"What is your favorite thing about this server?",
	"How many times a week do you wear the same pants?",
	"What is your nickname?",
	"What's the craziest thing that you have ever done without your parents knowing?",
	"What's the most childish thing that you still do?",
	"Have you ever stolen anything?",
	"Who here do you want to cuddle with the most?",
	"What is the last big goal you accomplished?",
	"What does your perfect vacation look like?",
	"In which sport would you like to become a professional?",
	"What animal most resembles your personality?",
	"What is the funniest youtube video you have ever seen?",
	"Have you ever lied to get out of a bad date?",
	"At what age did you learn that the other gender have different genitals?",
	"Do you people watch? If so, where do you like to do this most?",
	"If you could only listen to one song for the rest of your life, what would it be?",
	"What is your worst childhood memory?",
	"What do you look forward to doing when you are old?",
	"What do you think is the most valuable resource?",
	"If you could know one thing from the future what would it be?",
	"What is the one talent you wish you possessed?",
	"What's something that you thought you'd have already done by now, but haven't?",
	"If you make your phone or keys fall in the toilets, would you put your hand in it to get it back?",
	"If you were going to start your own business, what would it be?",
	"Are you in love or is it just lust?",
	"How is your day going?",
	"Which date do you prefer more, breakfast date or dinner date?",
	"Who here do you trust the most?",
	"What's something uncomfortable but you feel everyone should experience at least once in their life?",
	"Do you sing when no one is around?",
	"What are you currently juggling in your life?",
	"What's the biggest number of crushes you've had at one time?",
	"What is the most trouble that you ever got into in school?",
	"If you could only buy ten items at the grocery store to last the next week, what would you buy?",
	"If you had a chance to stay with a person one night who would you choose?",
	"Who is the best looking person you've ever been with?",
	"If you could make out with one Disney character, who would it be?",
	"Have you ever thrown up on a roller coaster?",
	"What uncommon thing would you like to see become more common?",
	"What is the longest amount of time that you have ever been away from home?",
	"How much money would you need in the bank to feel comfortable to retire today?",
	"What challenge would you like to see your best friend take on?",
	"What was your absolute worst bathroom experience?",
	"Where is your favorite place to go on vacation?",
	"What was your childhood nickname?",
	"How many times have you pulled an all nighter?",
	"Do you talk to yourself in the mirror?",
	"When was the last time you showered?",
	"What little thing do you do that you don't think many people notice?",
	"If you could shop for free in one store, which one would you pick?",
	"If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
	"What makes you unique?",
	"How big of a simp are you?",
	"If you had to wear a hat for the next week, what type of hat would you choose?",
	"How would you describe your personality?",
	"How much would you do to get your dream partner?",
	"Did you drink alcohol before you were legal to do so?",
	"What's the dumbest reason you've ever cried for?",
	"Who from here would you date and why?",
	"What is your relationship with your family?",
	"When was the last time you were nervous?",
	"Is the dress 'Black and Blue' or 'Gold and White'?",
	"Do you pick your nose?",
	"What do you think about spelling bee champions?",
	"What kind of pajamas do you wear to bed?",
	"If you were to work at a circus, what job would you choose?",
	"What was the unspoken scandal in your town when growing up?",
	"Are you scared of bugs?",
	"What joke do you think is funny that nobody ever laughs at?",
	"What is your favorite day of the week?",
	"What is a secret that you have never told anyone before?",
	"Do you have any weird habits? If so, what habits?",
	"Who was your first crush?",
	"Have you ever snuck a snack?",
	"Have you ever drawn on someone when they were asleep?",
	"Describe your first partner.",
	"Do you like bugs?",
	"What was your favorite childhood show?",
	"Have you ever skipped school?",
	"When was the last time you were caught in a lie?",
	"What's the naughtiest thing you've done in public?",
	"What is the funniest false thing you were able to convince others that's true?",
	"Do you have any scars? If so, how did you get the first one?",
	"If you could meet anyone in the world over dinner, who would you pick?",
	"Tell the craziest thing that you did this year.",
	"What is the best vacation you’ve ever been on?",
	"What was the most awkward part of a date you have been on?",
	"Where's the next place you want to visit?",
	"If you were invisible what is something you would do?",
	"Who was your worst kiss ever?",
	"Would you prefer to be smart or happy, and why?",
	"What bad decision did you make that actually turned out to be a good decision?",
	"What's something in your fridge right now that should probably be thrown out?",
	"Who is someone you need to contact that you haven't?",
	"What is the assumption that people make about you that's totally wrong?",
	"What is the worst thing that anyone has ever said about you?",
	"What's the meanest thing someone has ever said to you?",
	"If you had only 24 hours left to live, what would you do?",
	"Have you ever had a crush on two people at the same time?",
	"Do you still watch cartoons meant for children?",
	"What's your ideal person to date like?",
	"Do you play any sports?",
	"What is the craziest event that you have ever been to?",
	"Would you ever be polyamorous?",
	"Have you ever clipped your toenails in public?",
	"Have you ever pulled a prank on a teacher?",
	"When's the last time you snored loudly in front of others?",
	"What is something that you like that your parents do?",
	"What do you find extremely difficult that most people find simple?",
	"What's your best piece of advice for everyone here?",
	"What's something you're still angry about today?",
	"What, according to you, is the best thing about yourself?",
	"Which of the 4 seasons is your favorite? Which month?",
	"What's your biggest pet peeve?",
	"Do you think you're funny?",
	"Would you ever get a tattoo?",
	"Have you ever had to complain to management? Why?",
	"Could you go a week without junk food?",
	"When was the last time you told a lie?",
	"Would you ever go back with your ex?",
	"What part of history do you find most interesting?",
	"You know, I’ve always wondered... (fill in the blank)",
	"What do you appreciate more - love or money?",
	"What's something unpopular you wish more people would use?",
	"If you could be a professional athlete in any sport, what sport would you choose?",
	"Have you ever picked your nose and ate it?",
	"Where was your secret hiding place as a child?",
	"What was your last argument you had with someone about?",
	"Have you ever done something embarrassing around a former crush?",
	"When is the last time you cried?",
	"Have you spied on your sibling?",
	"What is your favorite emoji?",
	"Who is the worst cook you know?",
	"How do you entertain yourself when you're bored?",
	"If you could have someone else’s life for one day, whose would it be?",
	"Who is the sexiest person here?",
	"Who is the cutest person here?",
	"If you could be born as any famous historical person, who would it be and why?",
	"What was your first kiss like?",
	"If you could get one of your teachers/managers/bosses fired, who would it be?",
	"Who is the most innocent person in this server?",
	"What is the highest number of times you attempted an exam?",
	"What were you most afraid of when you were younger? Do you still have that fear?",
	"What's the best part of rain?",
	"Do you think Earth is the only inhabitable planet? Do you believe in aliens?",
	"How old do you think you will live to be?",
	"If you had to choose, would you rather be too hot or too cold?",
	"Have you ever pooped your pants?",
	"Do you currently have a crush on anyone?",
	"What's your favorite emoji?",
	"What's the weirdest thing you've done for your partner?",
	"What foreign languages would you like to learn?",
	"How difficult is it for you to try new things?",
	"What's the dumbest thing you've done recently?",
	"Have you lied about your age?",
	"Have you ever needed to go to the bathroom and not made it on time?",
	"What's one habit your partner has that annoys you?",
	"Have you ever said something out loud that you were thinking, without realizing you said it out loud? What was it?",
	"What are some things you don’t understand about the opposite sex?",
	"What is the worst present anyone has given you?",
	"How many selfies do you take per day?",
	"What thing did you do that got you into the most trouble?",
	"What's the last thing you had stuck in your teeth that you didn't notice until you got home?",
	"Have you ever failed something purposefully?",
	"What is the weirdest place you have ever shaved?",
	"What was your weirdest dream?",
	"Which famous person do you hate?",
	"Why wouldn't you marry your current partner?",
	"If it was possible to transplant your brain to stay alive for another 100 years, would you?",
	"Is there a mess under your bed?",
	"Have you ever forgotten to put on underwear?",
	"Which animal is most like you?",
	"What are you really really good at?",
	"What was your most traumatizing experience?",
	"Who is/was your longest crush?",
	"What's the embarrassing story that your parents used to tell others about you?",
	"When you're by yourself, what do you usually think about?",
	"Have you ever had surgery?",
	"What's your biggest weakness?",
	"If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?",
	"What's the stupidest thing you've done for a crush?",
	"If you could remove something that exists in this world forever, what would it be?",
	"Have you ever blamed something you did on another person?",
	"When was the last time you read a book?",
	"What are you most insecure about?",
	"What's something you find attractive that others may not?",
	"Have you smelled the inside of a seashell?",
	"What song's words did you totally mess up but you thought were correct?",
	"Have you ever taken money from your roommate?",
	"What's the worst gift you've ever given someone?",
	"If you could buy anything with $50, what would you get?",
	"Are you a planner or more of a go with whatever happens when it comes to travel?",
	"What is the craziest thing that you have ever done without your parents knowing?",
	"Have you ever been in a serious relationship?",
	"What's the most beautiful place you've ever been to?",
	"What's the riskiest thing you've done?",
	"Do you sneak snacks when nobody’s looking?",
	"What is the most recent life lesson you've learned?",
	"What's the meanest thing you've ever done?",
	"What's the scariest thing that's happened to you?",
	"What do you dislike about family gatherings?",
	"What's one trait that you think is super unattractive?",
	"What is the most annoying thing your roommate does?",
	"Would you consider yourself good at keeping secrets?",
	"Worst date you've ever been on?",
	"If you and one person in this room could be the last people on Earth left alive, who would that person be?",
	"What is your favorite game?",
	"What's the strangest thing you've ever found?",
	"What is the meanest thing you have done before today?",
	"Do you fall in love easily?",
	"How would you describe your sense of humor? Can you give an example?",
	"What will be your go-to story when you're old?",
	"Have you ever been grounded?",
	"Do you have a reddit account?",
	"What's your best memory with a friend?",
	"Is it better to read books in electronic form or actually hold the book?",
	"What's the best food you've ever had?",
	"What would you do if your parents left the house to you for a whole week?",
	"Would you get married?",
	"Have you ever experienced gender dysphoria?",
	"Who's more attractive, you or your best friend?",
	"What's the stupidest thing you've done in front of someone you liked?",
	"Would you see other people if your partner consented?",
	"Have you tried to befriend a stray dog or cat?",
	"What is your favorite quote?",
	"What would you do with $1,000?",
	"What do you wish you understood better?",
	"Have you ever dreamed of your partner?",
	"If you could try out any job for a day, what would it be?",
	"What's a useless skill you have?",
	"What got you into the most trouble at home?",
	"Would you let a parent look through your browsing history?",
	"What is the last lie you told?",
	"What bad thing have you done that no one else has found out about?",
	"Can you be alone in a dark room?",
	"What's something you lose sleep over?",
	"Have you ever peed around the toilet, but not in the hole?",
	"What's the strangest dream you've had?",
	"What's something others purchase that you simply can't understand why?",
	"What's the most romantic gift you've ever been given?",
	"What's the creepiest text you've gotten from a stranger?",
	"If you had to change one physical thing about yourself, what would it be?",
	"Do you have a favorite brand?",
	"Do you have a crush on anyone here?",
	"Who here do you want to kiss the most?",
	"Do you believe there is only one other person in the world for you or many?",
	"Do you prefer to be by yourself or with someone else?",
	"What is the most amount of time that you have ever spent in a hospital?",
	"What's the weirdest outfit you've ever worn in public?",
	"Did/Do you know that someone admired/s you?",
	"Where are you the most ticklish?",
	"Which cartoon character do you resemble the most?",
	"How many times have you snuck out of the house?",
	"Do you still have feelings for an ex?",
	"Who in this group is the most similar to you?",
	"What little thing instantly tells you that a person is good?",
	"In emergency situations, how do you react?",
	"If you could put one person in your family on mute for a day, who would it be?",
	"Would you ever get plastic surgery?",
	"What is the funniest dream that you have ever had?",
	"On any given day, what do you think you spend the most time doing?",
	"What is a gross thing you’ve done today?",
	"What is the meanest thing you've ever said/done to anyone?",
	"Have you ever pulled a prank on your teacher? Tell your story!",
	"What small stuff do you sweat even though you know you shouldn't?",
	"What do you think happens after we die?",
	"When was the last time you googled your own name?",
	"Do you know how to swim?",
	"What is the last encounter you had with a random stranger?",
	"If you will have the chance to change your face, whose face would you want to look like?",
	"What's the first thing you do in the morning?",
	"Have you ever fallen down the stairs?",
	"Do you have any secret hobbies?",
	"Do you keep a diary/journal?",
	"If Jurassic Park were real, would you visit it?",
	"Have you ever dressed up as the opposite sex?",
	"Have you held a tarantula?",
	"Do you sleepwalk?",
	"When did you last cry in front of another person? By yourself?",
	"What's the best way you've found to calm yourself when you get stressed?",
	"Have you ever been drunk?",
	"What's the worst job you could possibly have?",
	"Have you ever stolen from school or work?",
	"How many kids would you like to have?",
	"Have you ever lied about your age?",
	"What animal do you think best reflects your personality?",
	"If you knew the world was about to end, what would you do?",
	"When is your birthday?",
	"Are you currently where you want to be in life?",
	"Have you been on a train?",
	"What is the least favorite gift you’ve ever received?",
	"What food do you have a love-hate relationship with?",
	"Do you look up to anyone here?",
	"What is the strangest thing you have ever bought?",
	"Which parent are you closer to, and why?",
	"Name something you have done that you are totally ashamed of.",
	"If you had to kill one person here, who would it be?",
	"What is the one thing that you never got the chance to do?",
	"Who here would you want to trade lives with the most?",
	"What weird thing do you do when nobody else is around?",
	"Do you have any chores?",
	"Is there a personality trait that you'd like to adopt from one of your friends?",
	"Do you believe in any superstitions? If so, which ones?",
	"Are you on a dating site? Or have you ever considered signing up?",
	"Does your best friend call you their best friend?",
	"Where do you see yourself in 5 years?",
	"Describe your first kiss",
	"Can you describe your personal style?",
	"What's the most embarrassing thing that's happened when you asked someone out?",
	"What's the most difficult choice you were asked to make?",
	"Point to the person who will most likely eat other people to survive the apocalypse.",
	"Was there ever a time in your life that you thought you were going to die?",
	"Have you ever written a fan fiction?",
	"What's something about your last relationship that you could have improved?",
	"What's the funniest mispronunciation of your name that you've heard?",
	"What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
	"When is the last time you pretended to be sick when you weren't?",
	"Have you ever been rejected by someone?",
	"What topic can you bring up at a family gathering to instantly get everyone riled up?",
	"Do you like furries?",
	"Have you ever considered cheating?",
	"What's something small that makes you happy?",
	"Have you become a different person over the years?",
	"Who's the last person you called by the wrong name?",
	"What's the most ridiculous rumor you've heard about yourself?",
	"If you could change one thing about your childhood, what would it be?",
	"What is the grossest thing you've done today?",
	"Have you ever sneaked snacks when your parents weren't looking?",
	"What's your favorite dare?",
	"What is the least favorite gift you’ve received?",
	"Have you ever asked an ex out again?",
	"What's one job you'll never work?",
	"What's the most afraid you've ever been?",
	"Are you embarrassed by the music you listen to?",
	"What is your dream city to live in?",
	"Have you ever thrown up on a plane?",
	"What line from a song has had the biggest impact on you?",
	"What is the thing that you shouldn't know but you know entirely about it?",
	"Have you ever had feelings for a friend or family member’s significant other?",
	"Have you ever left a restaurant without paying the bill?",
	"If you could be reincarnated as anything, who or what would you be?",
	"What did you think you were good at but found out that you really weren't?",
	"What recent thing have you decided that you're completely over and done with?",
	"Do you prefer collectivism or individualism?",
	"Have you ever stalked someone? If you have, who was it?",
	"Who's the most photogenic person here?",
	"Do you know how to cook?",
	"What is the weirdest thing you've ever eaten?",
	"If you could choose the way you became a hero, what would the circumstances be?",
	"Have you ever been in love with any one of your close friends?",
	"What's the last thing that you gave up on? Are you happy or disappointed?",
	"What happened at your worst birthday party?",
	"Have you ever got caught cheating on an assignment?",
	"What do you think about your IRL friends?",
	"What is your least favorite food?",
	"What is the most annoying thing that your parents do?",
	"Whose voice do you like the most?",
	"What is the most disgusting thing that you have ever had in your mouth?",
	"What have you always wanted to become?",
	"Who taught you how to tie your shoes?",
	"What was the nastiest joke you ever played on someone?",
	"What's your most embarrassing swimming story?",
	"What game are you best at?",
	"What did you do to get suspended from school?",
	"Where are you ticklish?",
	"If you had a time machine, to which time period would you go?",
	"What is your most treasured memory?",
	"What situation is sure to make you cry?",
	"What is your opinion on tattoos?",
	"Who here is worst at flirting?",
	"What's a habit you wish you didn't have?",
	"Have you ever watched a movie or TV show that you know you’re not allowed?",
	"If you're being honest, what is your biggest flaw?",
	"Do you have a crush on someone? If so, who?",
	"What's the last thing you binged ate?",
	"Have you ever skipped a meal?",
	"Who is your personal hero",
	"Is there anyone that you're wondering about and if they're okay?",
	"What is something that you find mildly annoying, but not annoying enough to do anything about?",
	"How long could you go without eating your favorite food?",
	"What website do you waste the most time on?",
	"What's some small thing you recently noticed?",
	"Have you ever cheated in school?",
	"What are you thinking about at the moment?",
	"If you had to spend eternity with one person in this room, who would it be?",
	"What is your real GPA?",
	"What's the most embarrassing thing you've done in a taxi/carpool?",
	"Do you think you're attractive?",
	"What’s the first thing you’d do if you could inhabit the body of the opposite sex for one hour?",
	"Do you brush your teeth twice a day?",
	"What's the biggest lie you've ever told?",
	"What are the three qualities you feel are most important in a friend?",
	"What talent do you have that's embarrassing to share?",
	"Do you have something special that picks you up when you feel down? What is it?",
	"What would you do if you were invisible for a day?",
	"Which person here knows something about you that you wouldn't want revealed?",
	"What do you like most about your life?",
	"If you had to walk away from one technology in your life, what would it be?",
	"Do you have a special project you're currently working on?",
	"Have you ever walked into something while on the phone?",
	"What's the worst accident you ever had?",
	"What is your favorite sport?",
	"Have you ever shoplifted?",
	"What's the most spontaneous thing you've ever done?",
	"Who would be the best partner here?",
	"What is your favorite vegetable?",
	"Have you ever had a crush on anyone here?",
	"What one thing are you always losing track of?",
	"What is your favorite thing to do after school?",
	"Have you ever cheated to win a game?",
	"Would you stay naked at home if you lived alone?",
	"What are some things you think about when sitting on the toilet?",
	"If you could only ask one question to each person you meet, what would that question be?",
	"What has surprised you most in life?",
	"Pick one: money, fame or power.",
	"What's a song you relate to?",
	"Do you have a dream job in mind? What would it be?",
	"Who's the oldest person you've dated?",
	"Are you afraid of the dark?",
	"What does \"wife/husband/significant other material\" mean to you?",
	"Have you ever lied in this group chat, and if so, what was it about?",
	"What's the best compliment you ever received?",
	"What college do you plan on going to?",
	"What is the first letter in the name of your crush?",
	"What song gives you goosebumps?",
	"Have you ever thrown up in someone’s car?",
	"Would you have kids? If so, how many?",
	"What law have you broken the most in your life?",
	"Have you ever spent your parent's money on alcohol?",
	"Have you ever broken something and blamed someone else?",
	"Do you enjoy people watching?",
	"How old were you when you had your first kiss?",
	"Who is your role model?",
	"Who do you like to annoy the most?",
	"What's a food you like that no one else does?",
	"What's the most embarrassing thing that you've put on social media?",
	"Which person here knows something about you that you wouldn't want to be revealed?",
	"Do you believe in love at first sight?",
	"What's your most embarrassing nickname?",
	"If you had to ask yourself one question to get the most information out of you, what would that question be?",
	"If you could travel to the past and meet one person, who would it be?",
	"Who here do you think about the most?",
	"If you could say anything to your crush right now, what would it be?",
	"If you were a superhero, what would your power be?",
	"Who's the last person you simped for?",
	"Have you ever smoked?",
	"What mode of transportation have you never tried?",
	"Have you ever played sick because you didn't want to go to school?",
	"If you could lock someone up and throw away the key, would you and if so, who would that be?",
	"How old is the youngest person you've dated?",
	"If you could invent anything, what would it be?",
	"What's the most embarrassing item in your room?",
	"If you could give up happiness to never be sad, would you?",
	"What did you do to end up in detention at school?",
	"What's your current Golden Rule when it comes to living life?",
	"If you could have any person become a member of your family, who would you choose?",
	"What is something people think you'd never do but you have?",
	"Have you ever peed in a public pool?",
	"Which singer do you identify with and why?",
	"What do you consider the most difficult food to eat?",
	"What's something that makes you laugh?",
	"Have you ever confessed to someone that you like them?",
	"On a scale of 1 to 10, how good looking would you rate yourself?",
	"If you could be reborn as any nationality, which one would you pick?",
	"What country would like to live in if you had the chance?",
	"Which holiday do you think more people should celebrate?",
	"What is your favorite kind of clothing?",
	"Would you ever date someone you met online?",
	"If you could stop the time, what would you do?",
	"What book or movie character can you see in your own life?",
	"What's something that you would be willing to stay up all night to do?",
	"Do you think you'd be a good parent?",
	"What's the pettiest thing you've ever done?",
	"If you could make one of your dreams come true, which would it be?",
	"What one thing would significantly make your life better?",
	"What's something you thought your parents didn't know but found out later they did?",
	"If you could take away one bad thing in the world, what would it be?",
	"What is your favorite holiday and why?",
	"What are 5 things you want to do before you die?",
	"Have you watched a show you weren’t supposed to?",
	"If you could change the color of one thing, what would it be and why?",
	"Have you ever eaten something that was already thrown in the trash?",
	"When did you last shave and where on your body was it?",
	"What would you do if you saw a giraffe on the side of the road?",
	"Who has the best sense of style?",
	"How often do you shower?",
	"What was the last thing you did to get grounded?",
	"Describe yourself at age 30.",
	"Would you ever get back with an ex?",
	"How long does it take you to form an opinion about a person?",
	"How many grand-kids do you think you will have?",
	"How did you ruin clothing you really liked?",
	"Have you ever eaten dog food?",
	"Do you like reading for fun?",
	"What food combination do you eat that makes others cringe?",
	"Who here would you want to switch lives with for a day?",
	"When was the last time you had a hug?",
	"What is your dream pet?",
	"Do you think cheating is ever justified?",
	"What is your favorite thing about your partner?",
	"What's a funny story from your childhood?",
	"Have you ever called in sick from school/work? If so, when was the last time you've done it?",
	"How long you have been loving your crush and not confessed?",
	"Have you ever broken anything of someone else's and not told the person?",
	"What was a situation where you literally did a double take?",
	"Have you ever been physically defended by someone?",
	"Have you ever lied to your partner about being with others before or during your relationship?",
	"Have you ever kissed a friend's sibling?",
	"What would be a perfect pizza for you?",
	"Roblox or Minecraft?",
	"What is a common misconception about you?",
	"Have you ever embarrassed yourself in front of a crush?",
	"Have you ever snuck anyone into the house?",
	"Name a famous person that you would like to be friends with.",
	"What kind of person would you want to marry one day?",
	"What technology advance are you looking forward to in the future?",
	"What is the longest time that you think you could go without your cell phone?",
	"Do you have a reoccurring dream?",
	"Why did you break up with your last partner, and who broke up with who?",
	"What are your 5 favorite songs?",
	"Do you talk in your sleep?",
	"What would someone who doesn't know you well be most surprised about?",
	"What are the top three characteristics you feel are important for a person?",
	"What song currently speaks to you the most?",
	"How did you find out that Santa Claus is not real?",
	"What do you like to do on a rainy day?",
	"How often do you drink alcohol?",
	"Which person in the room do you think gossips the most?",
	"Are you a member of the LGBTQ+ community?",
	"What was the last big mistake you made?",
	"Why did you break up with your first girlfriend/boyfriend?",
	"What's your favorite song?",
	"Could you go one month without talking to your friends?",
	"What do you spend too much time doing?",
	"Have you ever peed in your pants from laughing too hard?",
	"What makes you feel insecure?",
	"Have you ever used your lunch money for something other than lunch?",
	"What was a past passion that you can't believe you were so passionate about?",
	"What would you do on the perfect first date?",
	"Who's the most bf/gf/significant other material?",
	"What’s something you love to do with your friends that you’d never do in front of your partner?",
	"If you had one week to live and had to marry someone here, who would it be?",
	"What's the worst thing you've ever said to your parents?",
	"How long did it take for you to come up with your current signature?",
	"Who do you care about the most?",
	"What is something you've never told anyone?",
	"If you could only pick one swear word to use for the rest of your life, what would it be?",
	"What question do you have that nobody has been able to give you a good answer to?",
	"When was a time that someone really betrayed your trust?",
	"Did you ever try to fake your report card grades?",
	"What is something that you would really like to try again?",
	"What's the story about the last time you cried?",
	"Are you often hard on yourself?",
	"How has the past year been for you?",
	"If you could be any animal, which one would you be?",
	"What do you see happening in your future?",
	"Have you ever blamed something that you have done on one of your siblings?",
	"Could you survive without any phone or internet for a month?",
	"What do you find is the most boring part of your life at the moment?",
	"Do you cover your eyes during scary movie scenes?",
	"What do you know is bad for you but you continue to do it anyway?",
	"What song do you secretly sing in the shower?",
	"What's your favorite joke?",
	"What is the most recent silly thing you did?",
	"What fear keeps you up at night?",
	"Have you ever snuck out of the house at night?",
	"If you could have the attention of the world for one minute, what would you say?",
	"If you could paint your room any color what would you choose?",
	"What's something you love to do with friends that you'd never do in front of strangers?",
	"How many people have you kissed?",
	"What was the last big argument you got into and who was it with?",
	"Have you ever given food to a homeless individual?",
	"If you were put in a random place in your city/town, could you find your way home?",
	"If you got a million dollars, but had to spend it in one day, what would you do with all of your money?",
	"What is your favorite kind of music to listen to?",
	"Has anyone ever walked in on you when going to the bathroom?",
	"What is your biggest insecurity?",
	"Have you ever used homework/being busy as an excuse not to go out with friends?",
	"Have you ever tried to write an excuse note for yourself?",
	"What's your favorite holiday?",
	"How do you make decisions?",
	"What's the scariest movie you've ever seen?",
	"Who did you vote for? Or who would you vote for?",
	"When is the last time you threw up?",
	"If the building was on fire, who out of this group would you pick to save?",
	"What's a skill you wish you had?",
	"If your house was burning, what 4 things would you grab?",
	"What is the easiest way to bring a smile to your face?",
	"Do you fall asleep easily?",
	"What is your biggest fear?",
	"What's on your bucket list?",
	"What's one thing you wish you could do, but can't do because of the consequences?",
	"Do you shower every day?",
	"Have you ever been on TV?",
	"If you were trapped on an island for 3 days, what would you take with you?",
	"Who is your boyfriend/girlfriend/partner?",
	"What's something that you use regularly that you wish you didn't have to?",
	"What's your favorite childhood memory?",
	"What is your favorite color?",
	"Do you have any family members that are farmers?",
	"What's your favorite music genre?",
	"What part of your body currently doesn't feel 100%?",
	"Do you have a nightmare travel story?",
	"What is the first thing that you do after school?",
	"Are there any words that you simply can't stand?",
	"What is your biggest fear in a relationship?",
	"What's the last thing you did alone and you enjoyed?",
	"What is your religion or spirituality?",
	"What's your dream vacation?",
	"What's something you wish you could tell your younger self?",
	"Who is your best friend?",
	"Who here do you trust the least?",
	"If you woke up one day to find out that you had become invisible, what is the first thing that you would do?",
	"Do you have any tattoos or piercings?",
	"If everyone here was a color, what color would each person be?",
	"What is something that you don't mind waiting for?",
	"Do you have a moment in your life you wish you could relive?",
	"What is the best random act of kindness you've ever witnessed?",
	"What is your favorite board game to play with your family?",
	"What is your least favorite music genre?",
	"How do you feel about end pieces of a loaf of bread?",
	"Which of your parents do you like more?",
	"Do you sing in the shower?",
	"Have you ever had a crush on a teacher?",
	"Do you remember your first crush?",
	"What is your pet's name?",
	"Who do you currently have a crush on?",
	"What habit can’t you seem to quit?",
	"Did you ever sneak outside your house after you were supposed to be asleep?",
	"What's a situation when you look back you should have gone ahead and done it?",
	"Have you ever cheated?",
	"What is your ideal school like?",
	"Can you name 5 things you wouldn't do for a million dollars?",
	"Does the thought of kissing the person to your left excite you?",
	"Have you ever kept a New Year's resolution? If yes, which one(s)?",
	"Name one of your guilty pleasure songs",
	"What is the most unique hobby you have?",
	"When was the last time you flossed your teeth?",
	"Have you ever skipped class/work, and if so, what did you do instead?",
	"Which emoji describes you best?",
	"Do you think that your partner thinks about marriage?",
	"What about you do you seem to get the most comments about?",
	"What's something that you find cute that you think is underrated?",
	"Do you have any apps on your phone that you've never used?",
	"What is the most disgusting thing you've ever done?",
	"How many exes numbers are currently in your phone?",
	"What is your weirdest habit?",
	"Would you break up with your partner for 1 million dollars? 1 billion?",
	"How old were you when you had your first crush?",
	"What are your thoughts on furries?",
	"Would you break up with someone over text?",
	"Who was the last person you talked to on the phone?",
	"Who is someone you recently thought about that you haven't seen or talked to in years?",
	"What can you talk about for hours?",
	"What's the last big mistake you made in front of others?",
	"Would you let a friend look through your browsing history?",
	"What is your favorite movie and why?",
	"What do you like to do when you are alone?",
	"What is your current go-to song to dance to when nobody is around?",
	"What is the worst thing about being your gender?",
	"What's the dumbest thing you've cried over?",
	"If you could own your own business one day, what would it be?",
	"Do you have any hidden talents?",
	"Have you ever gotten fired from a job? Why?",
	"If you knew the winning lottery numbers, would you keep them to yourself or share with others?",
	"Have you gotten over any bad habits?",
	"What emoji do you use way too much?",
	"What types of things do you procrastinate the most on?",
	"What's one thing you dislike about the opposite/different gender?",
	"Do you know the lyrics for your entire national anthem?",
	"What are you really-really good at?",
	"What's the most embarrassing thing you've ever done?",
	"What is the best lie you convinced someone that was true?",
	"Have you ever accidentally walked in on your parents naked?",
	"What's your plan for surviving a zombie invasion?",
	"Have you ever been in a police car, and if so, why?",
	"If you had to change the language you speak, which one would you choose?",
	"What country sounds interesting but you know very little about it?",
	"If you were stranded on an island, who is the one person you would want to be stuck with you?",
	"What's your most recent passion?",
	"When was the last time you cleaned your room?",
	"Have you ever shoplifted? What did you take?",
	"Have you ever let someone else get punished for something you did?",
	"Do you like mayonnaise?",
	"What or who are you always willing to make time for?",
	"What recent situation was nearly a disaster, but you were able to prevent it?",
	"What's the most amount of money you've ever found? What was the situation?",
	"What's your favorite soda?",
	"What's something interesting about you that few people know?",
	"What have you recently realized you have been doing wrong?",
	"What's your ideal relationship like, and who would you want to have it with?",
	"If you were the opposite gender for the day? What do you think you would wear? What would you do?",
	"Have you been given any good advice lately?",
	"Who is your favorite athlete?",
	"What's most important to you about your school/work environment?",
	"Out of everyone here, who would you pick to date if you had to pick someone?",
	"Which of your family members annoys you the most and why?",
	"How would you spend $1,000 to give the most happiness to the most number of people possible?",
	"What's something that you find difficult, but you think in your mind it should be easy?",
	"What's something about you today that the old you would find surprising?",
	"What's your opinion on cell phones?",
	"What flaw is enough to cause you to break off a relationship?",
	"What's the most disgusting thing you have ever seen?",
	"Do you have trust issues?",
	"How do you think you are most likely to die?",
	"Have you ever kissed someone in public",
	"What's the longest you've been without showering?",
	"Why did your last relationship break down?",
	"What makes you fall in love with someone?",
	"Would you ever swap partners with anyone?",
	"What languages can you speak?",
	"What is your \"guilty pleasure\"?",
	"How far back can you trace your family tree?",
	"If you could have anything in the world, what would it be?",
	"What future year are you most looking forward to arriving?",
	"Out of the last three people you texted, if you had to kiss one of them who would you pick?",
	"Who is your favorite singer?",
	"What's the worst false rumor that you've heard spread?",
	"On a scale of 1-10, how awkward are you?",
	"What's something you desperately want to hear?",
	"What is your favorite cartoon?",
	"Have you ever seen a ghost?",
	"Would you ever get a tattoo? What kind of tattoo would it be?",
	"What's something that you believe you'll never be able to do well?",
	"How are you, really?",
	"What is the strangest dream you've ever had?",
	"Have you ever gone on a blind date?",
	"What animal are you scared of?",
	"Did you tell a lie in this game of ToD? What was it and why?",
	"Who would you kick out of the server if you could?",
	"When you want to escape from everyone, where do you go?",
	"Who's your least favorite person in this server?",
	"Who can't you see crying in this server if you have to name only one?",
	"What is something that you would do that people would assume you would never do?",
	"Would you ever get on a dating website?",
	"What do you dislike most in a friend?",
	"If you were a food, what would you be and how would other people eat you?",
	"When was the last time you felt truly alive?",
	"What is the craziest thing you've ever watched?",
	"What's your sexual orientation? (If you're comfortable sharing)",
	"What's the way you find yourself procrastinating most?",
	"If you ever wrote a memoir, what would the title be?",
	"How many partners have you had?",
	"If you were a billionaire, what would you spend your time doing?",
	"What is your favorite ice cream flavor?",
	"What's the longest you've left food on the ground before eating it?",
	"If you could have any one thing in the world what would it be?",
	"Who do you go to when you are stressed?",
	"What compliment do you get the most?",
	"If you could be one person in this server for an hour, who would you be?",
	"What activity do you do where your mind wanders in thoughts the most?",
	"What's the story behind your favorite memento?",
	"How many selfies do you take a day?",
	"Have you ever broken something and not told anyone?",
	"What is one thing that you have always wanted to do but have not gotten around to it yet?",
	"What is the most shameful thing you've done in your life?",
	"Who here would be the worst person to date?",
	"What are your top five snacks?",
	"Have you showered today?",
	"Have you ever had a same-sex crush?",
	"What's the worst piece of advice you ever got from someone?",
	"What will your life legacy be?",
	"What makes you bored beyond measure?",
	"How many kids do you want?",
	"What are the top three qualities you admire in others?",
	"Where is the strangest place you've used the bathroom?",
	"What's something that you believe that most other people don't?",
	"Do you know how to dance?",
	"What's the worst excuse you tried to use on a teacher or parent?",
	"What's something you've wasted too much money on?",
	"How would you spend your time if the internet didn't exist?",
	"Have you ever taken a long shot that worked out?",
	"Do you bite your nails?",
	"Is time currently passing quickly or slowly for you?",
	"Did you have an imaginary friend when you were growing up?",
	"How young were you when you started buying your own alcohol? Did you need a fake ID?",
	"What is the most annoying thing that one of your siblings does?",
	"What's your really weird secret collection?",
	"What's the worst lie you've been told?",
	"What do you like on your toast?",
	"Have you ever pulled a prank on your teacher?",
	"What was the last lie you told your significant other?",
	"Could you survive without your phone for a week?",
	"Do you have someone you miss a lot, but don't want to think about? why?",
	"What was the nastiest prank you ever played on someone?",
	"What is the longest you have gone without sleep?",
	"What do you wish you had more talent doing?",
	"Who in your family can you not believe you're related to?",
	"Who was your first partner?",
	"At what age did you think you become an adult and when do you actually think you did?",
	"What's the weirdest thing about you? Are you proud of it?",
	"What do you value most in a relationship?",
	"What video have you made that you're most embarrassed about?",
	"Are you a left-handed or right-handed?",
	"When was the last time you picked your nose without a tissue?",
	"Do you like doing chores?",
	"What's your favorite thing about your crush?",
	"What do you like most about the person asking you this question?",
	"What would you do with a million dollars?",
	"What is the best thing that you have ever had to eat?",
	"What's a weird food combination you actually like?",
	"What's your biggest first world problem?",
	"What is the best party that you've ever been to?",
	"What things are you shallow about?",
	"Who is your current crush?",
	"What is your most bizarre talent?",
	"What's the most interesting conversation you eavesdropped on?",
	"What did you recently learn the hard way?",
	"What do you consider the best decision you've made thus far in your life?",
	"Would you marry your partner?",
	"Of all the things you've bought in your life, what has been the worst purchase?",
	"Have you ever been canceled for something?",
	"What is an unpopular opinion that you have?",
	"What would you do if you could retire at 40?",
	"What is the next skill that you'd like to learn really well?",
	"What's the longest you've ever gone without taking a bath?",
	"What would you do if you could stop time?",
	"Have you ever broken a bone?",
	"What's the best trick someone has ever played on you?",
	"Have you ever had a crush on a friend's partner?",
	"How much damage could your best friend do to you if you ever had a falling out?",
	"What is your favorite movie?",
	"What is a restaurant you refuse to eat at and why?",
	"What is the best thing that can happen in the first 5 minutes after waking up?",
	"Would you prefer to date someone younger or older than you?",
	"Who is the nicest person here?",
	"Have you ever started an unintended fire?",
	"Describe your worst kiss ever.",
	"When was the most embarrassing time that you passed gas?",
	"Have you ever let someone take the blame for something you did?",
	"What kind of candy would you want to be in your birthday present?",
	"What can you sometimes be prejudiced about?",
	"Who has the best voice in the server?",
	"Have you ever accidentally destroyed something that was important to someone else?",
	"If a genie came out of a lamp, what would your 3 wishes be?",
	"What sound will instantly melt your heart?",
	"Would you go behind a friend's back with a crush?",
	"Do you think you're more like your mom or your dad?",
	"What is the one highest standard you hold yourself to?",
	"Is there a mess in your closet?",
	"What is your least favorite thing about your best friend?",
	"Have you ever given cheating a serious thought?",
	"Have you ever done something that you wish you apologized for when you had the chance?",
	"Have you ever had a crush on a co-worker?",
	"Do you like to exercise?",
	"When was the last time you peed yourself?",
	"Have you ever cried while it was raining so they wouldn't notice you were crying?",
	"What is the most recent fact you learned that surprised you?",
	"What animal are you most scared of?",
	"What do you know how to do that's useless?",
	"When was the last time you spied on someone's text messages?",
	"What's your most useless skill?",
	"What is the sweetest thing that someone could do for you?",
	"If you could trade places with anybody in the world, would you do it? If yes, who would it be?",
	"Who is your ex?",
	"What do you stress about the most?",
	"What do you value most in a friendship?",
	"Without saying the category, what are your top five?",
	"Have you ever lied to your parents about what you were doing after school?",
	"Would you consider yourself popular?",
	"What was your most recent experience of going down the rabbit hole?",
	"What gender do you think angels are?",
	"What do you think is your biggest physical flaw?",
	"What's the worst thing you have ever done?",
	"How do you feel about social media?",
	"What is one embarrassing fact we should know about you?",
	"What is something you stole?",
	"Is kissing someone else cheating?",
	"Have you ever shared a secret you promised you wouldn't?",
	"What is your favorite anime?",
	"Who here are you most jealous of?",
	"How would you rate your looks on a scale from 1-10?",
	"What's the best comeback you've ever heard?",
	"Who is your worst enemy?",
	"How many real Discord friends do you have?",
	"Do you overthink a lot?",
	"Have you ever been caught checking someone out?",
	"Who is one person you wish was still in your life?",
	"What is your favorite season of the year?",
	"Who in this room do you think would be the worst date?",
	"What is the most attractive quality in a partner?",
	"Who are 5 famous people that you would like to have dinner with? They can either be dead or alive.",
	"Do you have any family members that are doctors/nurses/pharmacists/etc?",
	"What would be the best thing about losing your hearing?",
	"Are you a morning or night person?",
	"What's your definition of success? Has it changed over time?",
	"Would you consider yourself decisive or indecisive?",
];

pub static DARES: [&str; 272] = [
	"Lick your nose",
	"Voice act a cartoon character of the group's choice.",
	"Show everyone a picture of you when you were young.",
	"Call one of your parents and then tell them they are grounded for a week",
	"Change your Discord PFP to whatever the group decides.",
	"Prank call McDonald's",
	"Type with only one hand for the next minute",
	"Take a picture of you doing over-done ducklips.",
	"Rickroll someone",
	"Post a selfie.",
	"Listen to a country song",
	"Slap the last person who talked besides yourself.",
	"Pretend to be another player for the next round",
	"Tell the group something about you that you've never told them before",
	"Pair everyone here up into couples.",
	"Put your face in a bowl of ice cold water for 30 seconds.",
	"Tell the other players something you've never told anyone before",
	"Share your phone's wallpaper",
	"Send a picture of your favorite stuffed animal.",
	"Let someone here do your makeup.",
	"Share one of your playlists",
	"Tell your best friend that you'll always be with them no matter what :)",
	"Show everyone the last YouTube video you watched.",
	"Share the most recent photo on your phone with the group.",
	"DM someone \"hi\" and respond with \"banana\" to everything they say",
	"Send a sentence without the words: but, a, the, or",
	"Sharpie an embarrassing message on any part of the body covered by clothing.",
	"Call someone you're playing with 'mommy' or 'daddy'",
	"Spin an imaginary hula hoop around your waist for 1 minute.",
	"Write a love poem to the first person in the offline list",
	"Text your crush and tell them how cool they are",
	"Send a message to the person at the bottom of your DMs list",
	"Imitate a behavior of who you like.",
	"Type with only one finger for the next minute",
	"Let the group pose you in an embarrassing position and take a picture.",
	"Show the list of people in your DMs.",
	"Ask a friend for their mom's phone number",
	"Show the group an embarrassing picture of you.",
	"Tell your crush that you don't love them.",
	"Use a furry pfp for 24 hours",
	"Have someone in the group ask a question that you must answer",
	"Ghost ping the person you like.",
	"Tie your shoe strings together and try to walk to the door and back",
	"Pretend to date someone for a day.",
	"Kiss someone for 1 minute.",
	"Prank call your enemy",
	"Text the third person in your message history 'last night was great' with a heart.",
	"Send a picture of the item closest to your phone.",
	"Google images of the first word that comes to your head and send the first image",
	"Send the worst meme you've made",
	"Show the last DM you sent without context",
	"Let someone go through your YouTube history and read it out to the group.",
	"Tell your crush you hate them.",
	"Name as many countries as you can",
	"Type with only the left side of your keyboard for the next minute",
	"Send a passive-aggressive message to a friend",
	"Show the group a picture of one person you find very attractive.",
	"Text your crush about how much you like them, but don't reply to them after that.",
	"Show everyone the funniest meme in your camera roll.",
	"Set your cell phone language to Spanish for the next 10 minutes",
	"Text to your bff 'I kinda have a crush on you wanna go out?' And don't reply to any of their messages.",
	"List three things you like about your crush.",
	"Send a meme you've made",
	"Send your favorite meme",
	"Describe everyone in the room in three words.",
	"Text your crush 'I love you'.",
	"Send a message to someone you haven't talked to in a year",
	"Lick the wall.",
	"Go to the first person you know on your instagram feed and like every photo on their profile.",
	"Invite anyone in the group's choosing to join the call.",
	"Call your parents and talk about the weather in a british accent",
	"Tell the other players something they don't know about you",
	"Change your phone wallpaper to the choice of the group for 7 days.",
	"Make a poem using the words orange and moose",
	"Exchange a clothing item with the player on your right.",
	"Yell a swear word really loudly",
	"Message someone you argued with and tell them that you're sorry.",
	"Show everyone your screen time",
	"Send a picture of your eyes.",
	"Hug the object/person nearest you.",
	"Take a shot of mustard or ketchup.",
	"Make up a rap and sing it for 30 seconds",
	"Kiss the player you think looks the cutest.",
	"Choose 3 people here and tell them the latest lie you told to them here (not in DMs).",
	"Delete the last 10 pictures in your camera roll permanently (remove them from recently deleted too).",
	"Take a picture of yourself and show it to the group.",
	"Eat an ice cube",
	"Post your favorite pet photo",
	"List the things on your desk",
	"Name one thing you would change about each person here.",
	"Show everyone something you wrote/drew when you were younger.",
	"Set an alarm for 4 A.M. tomorrow morning.",
	"Use Discord light theme for an hour",
	"Talk in an accent for the next 10 minutes.",
	"Tell everyone about your last kiss.",
	"Eat a packet of hot sauce.",
	"Let the group look through your phone for 30 seconds.",
	"Let someone go through your Amazon purchase history and read it out to the group.",
	"Give your friends your unlocked phone for 30 seconds",
	"Lick the neck of the person next to you.",
	"Block the fifth person in your DMs.",
	"Change your status to \"I'm a furry, deal with it uwu\"",
	"Screenshot your most played songs and show it to the group.",
	"Send a Snapchat to your ex.",
	"Slap your face.",
	"Do an impression of someone until another player can guess who you are",
	"Send a screenshot of the bottom of your DMs list",
	"Tell your best friend that you're a furry",
	"Show the group the insides of your closet.",
	"Don't touch your phone for an hour after the game is over.",
	"Try not to blink for as long as possible",
	"Everyone go get a drink of water - ToD Bot Team",
	"Ask someone in this server out on a date.",
	"Sing a song of the groups choice, in a VC.",
	"Act like an animal for the next minute",
	"Make an owo emote for the group.",
	"Use your non-dominant hand for an hour",
	"Tweet '*insert popular band name here* fans are the worst' and don't reply to any of the angry comments.",
	"Change your nickname/username to whatever the group wants.",
	"Send your crush something wholesome",
	"Stand up and spin in a circle three times.",
	"Type a sentence about food with your eyes closed.",
	"Do your best impersonation of the question asker or someone in the group.",
	"Put on makeup if you don't wear makeup and it's available, take off all your makeup if you're wearing it.",
	"Fake cry for the group.",
	"Spin around for 30 seconds",
	"Ghost ping someone",
	"Lick the floor.",
	"Howl like a wolf",
	"Send your partner a fake breakup message.",
	"Rate everyone here 1-10 in terms of personality.",
	"Show everyone here your screen time.",
	"Act like a dog for 1 minute.",
	"Everyone here take a snack break - ToD Bot team.",
	"Let the group choose your profile picture for the next day",
	"Let the group decide your outfit for tomorrow.",
	"Send knee pics to the group.",
	"Spin around 10 times and try to walk straight.",
	"Try to lick your elbow",
	"Tell the 3rd person in your DMs that you love them",
	"Send your youtube watch history",
	"Send the fifth person in your message history 20 seconds of keyboard spam.",
	"Do as many pushups or situps as you can in a minute.",
	"Describe the object closest to you until the group guesses the object.",
	"Send a photo of where you are",
	"Point out the worst dressed person in the room.",
	"Show everyone an embarrassing childhood picture of you.",
	"Text the first six people in your message history 'a' and don't reply if they bring it up.",
	"Name as many types of car as you can",
	"Sit on one person's lap for two minutes.",
	"Do an impression of your favorite celebrity",
	"Tell your funniest joke to the group.",
	"Send your worst playlist",
	"Try to tickle yourself",
	"Take a shot of lemon juice, and take one more every time someone picks dare.",
	"Call your crush and serenade them.",
	"Kiss the person who you think is the best friend to you.",
	"Call your crush and try to make conversation for a minute.",
	"Lick the bottom of your shoe/foot.",
	"Sing a lullaby in VC.",
	"Sit in the lap of the person to your left for 3 turns.",
	"Send a weird picture of yourself.",
	"Send the first word that comes to your mind right now",
	"Name every ocean",
	"Have a matching pfp with who you like for 3 days.",
	"Ask the first person in your DMs to marry you.",
	"Send the most furry-like message possible",
	"Ping a friend to join!",
	"Hum a song of your choice, don’t stop until someone correctly guesses the song",
	"Play a song of the next person's choosing.",
	"Draw a face around your belly button.",
	"Show everyone the last picture in your camera roll.",
	"Call a random person and sing happy birthday to them",
	"Post the fanciest photo you've ever taken",
	"Ask a random person in this server if you've met them before",
	"Put ice in your clothes and wait until it melts.",
	"Sing a song for the group.",
	"Do a cartwheel.",
	"Post your favorite photo on your phone",
	"Talk in a very deep voice for the next round",
	"Talk in an accent for the next 3 rounds",
	"Type with your fists for the next minute",
	"Send a message only using your toes",
	"Type without vowels for the next minute",
	"Prank call your crush",
	"Text your best friend \"something crazy just happened\" and don't respond",
	"Have everyone here list something they like about you",
	"Scream at the top of your lungs whatever the chat wants.",
	"Do a yoga pose for 3 minutes.",
	"Kiss the person to your left, either on the hand or cheek.",
	"List everyone as the emoji(s) you think best fits them.",
	"Type as fast as you can for the next minute",
	"Send the pleading emoji to the 2nd person in your DMs",
	"Send a paragraph to your crush about 3 things you love about them.",
	"Send every curse word you can think of in chat.",
	"Do an impression of your most annoying teacher",
	"Prank call the last person that called you",
	"Paint your fingernails with a crayon",
	"Make up a country song off the top of your head",
	"Post an embarrassing photo on your Instagram story.",
	"Text your ex and ask them 'How's it going?'.",
	"Ask your dad for a dad joke and send it",
	"Eat a piece of paper.",
	"Take a sniff of everyone playing.",
	"Let the group decide your status for 7 days.",
	"Don't charge your phone until it dies.",
	"Text your parents \"something crazy just happened\" and share what they say",
	"Describe the last dream you had.",
	"Answer the next truth question with complete honesty",
	"Tell everyone your honest opinion of the person who sent this command.",
	"Send the 8th person in your DMs something embarrassing.",
	"Send your favorite joke",
	"Spill the last secret someone told you.",
	"Do whatever someone else wants for the rest of the day.",
	"Play the last song you listened to. No lying!",
	"Name as many cities as you can",
	"Post the latest photo you took to instagram",
	"Link everyone to the last song you listened to.",
	"Show your lock screen and wallpaper.",
	"Tell your crush that you like them",
	"List everyone as the kind of animal you see them as.",
	"Speak only in emojis for the next 5 minutes",
	"Call your first DM for no reason",
	"Everything you say for the next 5 rounds has to rhyme.",
	"Show everyone your recent calls",
	"Say UWU for as long as possible",
	"Act like a furry to the 5th person in your DM list's DMs",
	"Screen share your search history from today.",
	"Rate everyone here 1-10 in terms of looks.",
	"Show everyone the earliest picture in your camera roll.",
	"Close your eyes and send a blind message to a random person",
	"Sit on the lap of the person you like for 5 mins.",
	"Kiss someone of your same gender.",
	"Send the last meme you saved to your phone",
	"Show everyone your frequently used emoji list.",
	"Let your friends post something on your social media",
	"Switch to Discord light mode for the rest of the day",
	"Propose to someone in the group",
	"Tell the group about your worst experience on a date.",
	"Send a picture of your pet.",
	"Curse as badly as you can for 20 seconds.",
	"Send a song you're embarrassed to listen to",
	"Send one of your favorite playlists!",
	"Name as many types of food as you can",
	"Call someone random, and say everything in a british accent",
	"Talk with a Russian accent for the next 3 rounds",
	"Tell the last person you texted that you're pregnant/got someone pregnant.",
	"Send your best friend \"I hate you\" and don't respond to any of their messages.",
	"Hold your breath for 10 seconds",
	"Hold hands with the player on your right for 3 minutes.",
	"Send a photo of your desk",
	"Ask someone random for a hug",
	"Send 5 pleading emojis to the last person you DMed",
	"Imitate your least favorite celebrity",
	"Ask someone out of a gender you aren't attracted to.",
	"Send/say the alphabet backwards",
	"Describe your crush, but don't give it away.",
	"Show the group your latest YouTube searches",
	"Show everyone here the last 5 messages with the last person you messaged/messaged you.",
	"Show everyone your DMs list",
	"Show the last text message you have received without context .",
	"Prank call your best friend",
	"List everything in your wallet",
	"Breakdance for the group.",
	"Show everyone here the worst picture of you that you can find.",
	"Send a text to your crush explaining your favorite movie plot in vivid detail.",
	"Ask your crush who they have a crush on.",
	"Text the last 6 people in your DMs 'I love you'.",
	"Call a relative. The group can ask one question.",
	"Post the oldest photo on your phone",
	"Lick someone's hand.",
	"Be really annoying for the next minute",
];
